name: habercraft_pro
description: "HaberCraft Pro - Interaktif Haber Tüketim Platformu"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  video_player: ^2.8.2
  http: ^1.1.2
  shared_preferences: ^2.2.2
  flutter_staggered_grid_view: ^0.7.0
  curved_navigation_bar: ^1.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
